// Code generated by protoc-gen-go.
// source: honeytrap/proto/protocol.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	honeytrap/proto/protocol.proto

It has these top-level messages:
	Payload
*/
package protocol

import proto1 "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type Payload struct {
	Token            *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	LocalAddress     *string `protobuf:"bytes,2,req,name=localAddress" json:"localAddress,omitempty"`
	RemoteAddress    *string `protobuf:"bytes,3,req,name=remoteAddress" json:"remoteAddress,omitempty"`
	Protocol         *string `protobuf:"bytes,4,req,name=protocol" json:"protocol,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto1.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}

func (m *Payload) GetLocalAddress() string {
	if m != nil && m.LocalAddress != nil {
		return *m.LocalAddress
	}
	return ""
}

func (m *Payload) GetRemoteAddress() string {
	if m != nil && m.RemoteAddress != nil {
		return *m.RemoteAddress
	}
	return ""
}

func (m *Payload) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *Payload) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}
