// Code generated by protoc-gen-go.
// source: honeycast/proto/protocol.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	honeycast/proto/protocol.proto

It has these top-level messages:
	Message
*/
package protocol

import proto1 "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type Message struct {
	LocalAddress     *string `protobuf:"bytes,1,req,name=localAddress" json:"localAddress,omitempty"`
	RemoteAddress    *string `protobuf:"bytes,2,req,name=remoteAddress" json:"remoteAddress,omitempty"`
	Token            *string `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto1.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetLocalAddress() string {
	if m != nil && m.LocalAddress != nil {
		return *m.LocalAddress
	}
	return ""
}

func (m *Message) GetRemoteAddress() string {
	if m != nil && m.RemoteAddress != nil {
		return *m.RemoteAddress
	}
	return ""
}

func (m *Message) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}
